import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { m, motion } from "framer-motion";
import { ArrowTopRightIcon } from "@radix-ui/react-icons";
import { FirstLetterChanged, Header, Menu } from ".";
const hoverEffect = {
  rest: {
    scaleX: "0",
    transformOrigin: "bottom right",
  },
  hover: {
    scaleX: "1",
    transformOrigin: "bottom left",
  },
};

const arrowEffect = {
  rest: {
    translateY: "-110%",
    translateX: "110%",
    transformOrigin: "bottom",
  },
  hover: {
    translateY: "0%",
    translateX: "0%",
    transformOrigin: "top",
  },
};

const HoverLink = ({ text, link }: { text: string; link: string }) => {
  return (
    <Link href={link}>
      <div className="w-auto cursor-pointer font-inter text-[0.8vw] font-medium  text-[#1C1C1C]">
        <motion.div
          initial="rest"
          whileHover="hover"
          className="block w-min cursor-pointer transition-all duration-500"
        >
          <div className="flex w-full items-center justify-between space-x-1 overflow-hidden">
            <span>{text}</span>
            <motion.div
              className="transition-transform duration-700 ease-out "
              variants={arrowEffect}
            >
              <ArrowTopRightIcon className="text-[0.8vw]" />
            </motion.div>
          </div>
          <motion.div
            variants={hoverEffect}
            className="h-[1px] w-full bg-black  transition-transform duration-700 ease-out "
          ></motion.div>
        </motion.div>
      </div>
    </Link>
  );
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cornelius Denninger - Homepage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen overflow-hidden bg-[#ebebeb] px-12 py-12 font-inter">
        <Header />
        <div className="mt-24 text-center text-7xl font-medium ">
          <h1 className="text-[5.8vw]  bg-blend-difference ">
            <span className="font-roxborough font-medium italic tracking-tighter  bg-blend-difference ">
              Let&apos;s collaborate
            </span>{" "}
            <br />{" "}
            <span className="font-inter font-light tracking-tighter">
              and make good shit together
            </span>
          </h1>
        </div>
        <div className="mt-24">
          <Menu />
        </div>
        <div className="absolute bottom-16 grid grid-cols-2 gap-8  ">
          <div className="flex space-x-16 ">
            <div>
              <h5 className="text-[0.8vw] font-medium text-[#878787]">
                Social
              </h5>
            </div>
            <ol className="space-y-1">
              <li>
                <HoverLink text="LinkedIn" link="#" />
              </li>
              <li>
                <HoverLink text="Twitter" link="https://twitter.com/colodenn" />
              </li>
              <li>
                <HoverLink text="GitHub" link="https://github.com/colodenn" />
              </li>
            </ol>
          </div>
          <div className="flex space-x-16 ">
            <div>
              <h5 className="text-[0.8vw] font-medium text-[#878787]">
                Portfolio
              </h5>
            </div>
            <ol className="space-y-1">
              <li>
                <HoverLink text="GitHub" link="https://github.com/colodenn" />
              </li>
              <li>
                <HoverLink text="Resumee" link="https://codenn.de" />
              </li>
            </ol>
          </div>
          <div className="flex  space-x-16 ">
            <div>
              <h5 className="text-[0.8vw] font-medium text-[#878787]">Email</h5>
            </div>
            <ol className="space-y-1">
              <li>
                <HoverLink
                  text="cornelius.denninger@gmail.com"
                  link="mailto:cornelius.denninger@gmail.com"
                />
              </li>
            </ol>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
