import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { m, motion } from 'framer-motion';
import { FaceIcon, ArrowBottomRightIcon, ArrowTopRightIcon } from "@radix-ui/react-icons"
const hoverEffect = {
  rest: {
    scaleX: "0",
    transformOrigin: "bottom right",
  },
  hover: {
    scaleX: "1",
    transformOrigin: "bottom left",
  },

}

const arrowEffect = {
  rest: {
    translateY: "-110%",
    translateX: "110%",
    transformOrigin: "bottom"
  },
  hover: {
    translateY: "0%",
    translateX: "0%",
    transformOrigin: "top"
  },
}

const HoverLink = ({ text, link }: { text: string, link: string }) => {
  return (
    <Link href={link}>
       <div className="w-auto cursor-pointer text-xs text-[#1C1C1C]">
      <motion.div initial="rest" whileHover="hover" className="transition-all cursor-pointer duration-500 block w-min">
        <div className="flex justify-between items-center space-x-1 w-full overflow-hidden">
          <span>{text}</span>
          <motion.div className="transition-transform ease-out duration-700 " variants={arrowEffect}><ArrowTopRightIcon /></motion.div>
        </div>
        <motion.div variants={hoverEffect} className="transition-transform duration-700 w-full  bg-black h-[1px] ease-out "></motion.div>
      </motion.div>
    </div>
    </Link>
   
  )
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cornelius Denninger - Homepage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen overflow-hidden bg-[#ebebeb] px-12 py-12">
        <Header />
        <div className="text-center mt-24 font-medium text-7xl ">
          <h1>Lets collaborate <br/> and make good shit together</h1>
        </div>
        <div className="mt-24">

        <Menu />
        </div>
        <div className="absolute bottom-16 grid grid-cols-2 gap-8  ">
        <div className="flex space-x-16 ">
          <div>
            <h5 className="text-xs font-semibold text-[#878787]">Social</h5>
          </div>
          <ol className="space-y-1">
            <li>
              <HoverLink text="LinkedIn" link='#' />
            </li>
            <li>
              <HoverLink text="Twitter" link='#'  />
            </li>
            <li>
              <HoverLink text="GitHub" link='#'  />
            </li>
          </ol>
        </div>
        <div className="flex space-x-16 ">
          <div>
            <h5 className="text-xs font-semibold text-[#878787]">Portfolio</h5>
          </div>
          <ol className="space-y-1">
            <li>
              <HoverLink text="GitHub" link='#'  />
            </li>
            <li>
              <HoverLink text="Resumee" link='#' />
            </li>
          </ol>
        </div>
        <div className="flex  space-x-16 ">
          <div>
            <h5 className="text-xs font-semibold text-[#878787]">Email</h5>
          </div>
          <ol className="space-y-1">
            <li>
              <HoverLink text="cornelius.denninger@gmail.com" link='#' />
            </li>
         
          </ol>
        </div>
        </div>
      </main>
    </>
  );
};

const Header = () => {
  return (
    <>
      <div className="flex justify-between">
        <div className="w-full flex justify-start">
          <div className="flex  justify-between space-x-6 items-center"><div className="overflow-hidden h-max">
            <Image src={"/logo.svg"} width={30} height={30} alt="logo" />
          </div>
            <div className="  text-xs  leading-tight flex flex-col">
              <span className="">Open for any</span>

              <span className="">collaborations and offers</span>
            </div>
          </div>

        </div>
        <div className="w-full flex justify-center"><h1 className="font-bold text-xl">
          <Link href={"#"}>CODENN.</Link>

        </h1></div>
        <div className="w-full flex justify-end">
          <div className="flex flex-col text-xs ">
            <span>Portfolio</span>
            <span className="flex justify-end">Vol.1 <span>-</span></span>
          </div>
        </div>
      </div>
    </>
  )
}

const Menu = () => {
  return (
    <>
      <div className="flex text-xs justify-between items-center">
        <div className="">
          <p className=" text-[#878787]">01</p>
          <p className="font-medium">Work</p>
        </div>
        <div className="">
          <p className=" text-[#878787]">02</p>
          <p className="font-medium">About</p>
        </div><div className="">
          <p className=" text-[#878787]">03</p>
          <p className="font-medium">Playground</p>
        </div><div className="">
          <p className=" text-[#878787]">04</p>
          <p className="font-medium">Contact</p>
        </div><div className="">
          <p className="font-medium">©2023</p>
        </div>
      </div>
    </>
  )
}

export default Home;
