import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cornelius Denninger - Homepage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen overflow-hidden bg-[#ebebeb] px-12 py-12">
        <Header />
        <div className="my-24">

          <h1 className="text-9xl text-center font-roxborough">Cornelius Denninger</h1>
        </div>
        <Menu />
        <div className="flex  justify-between items-center">
          <div className="w-full flex justify-center">
            <p>Lorem impsim asfkasd lapslfe msacmoe  xgflawe dfjaweo</p>
          </div>
          <div className="my-24 flex w-full justify-center">
            <Image src={"/person.png"} alt="Person" height={200} width={200} />
          </div>
          <div className="w-full flex justify-center">
            <p>Lorem impsim asfkasd lapslfe msacmoe  xgflawe dfjaweo</p>
          </div>
        </div>
      </main>
    </>
  );
};

const Header = () => {
  return (
    <>
      <div className="flex justify-between">
        <div className="w-full flex justify-start">
          <div className="flex  justify-between space-x-2 items-center"><div className="overflow-hidden h-max">

            <Image src={"/logo.svg"} width={30} height={30} alt="logo" />
          </div>
            <div className="  text-xs font-medium leading-tight flex flex-col">
              <span className="">Open for any</span>

              <span className="">collaborations and offers</span>
            </div>
          </div>

        </div>
        <div className="w-full flex justify-center"><h1 className="font-bold text-xl">
          <Link href={"#"}>CODENN.</Link>
        
        </h1></div>
        <div className="w-full flex justify-end">
          <div className="flex flex-col text-xs font-medium">
            <span>Portfolio</span>
            <span className="flex justify-end">Vol.1 <span>-</span></span>
          </div>
        </div>
      </div>
    </>
  )
}

const Menu = () => {
  return (
    <>
      <div className="flex text-xs justify-between items-center">
        <div className="">
          <p className=" text-[#878787]">01</p>
          <p className="font-medium">Work</p>
        </div>
        <div className="">
          <p className=" text-[#878787]">02</p>
          <p  className="font-medium">About</p>
        </div><div className="">
          <p className=" text-[#878787]">03</p>
          <p className="font-medium">Playground</p>
        </div><div className="">
          <p className=" text-[#878787]">04</p>
          <p className="font-medium">Contact</p>
        </div><div className="">
          <p className="font-medium">©2023</p>
        </div>
      </div>
    </>
  )
}

export default Home;
