import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { useState } from "react";
import { clsx } from "clsx";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cornelius Denninger - Homepage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen overflow-hidden bg-[#ebebeb]  py-12">
        <Header />
        <div className="my-24">
          <h1 className="text-center font-roxborough text-9xl">
            Cornelius <span className="">Denninger</span>
          </h1>
        </div>
        <Menu />
        <div className="flex  items-center justify-between">
          <div className="flex w-full justify-center text-center">
            <p>Lorem impsim asfkasd lapslfe msacmoe xgflawe dfjaweo</p>
          </div>
          <div className="my-24 flex w-full justify-center">
            <Image src={"/person.png"} alt="Person" height={200} width={200} />
          </div>
          <div className="flex w-full justify-center text-center">
            <p>Lorem impsim asfkasd lapslfe msacmoe xgflawe dfjaweo</p>
          </div>
        </div>
      </main>
    </>
  );
};

const Header = () => {
  return (
    <>
      <div className="flex justify-between px-12">
        <div className="flex w-full justify-start">
          <div className="flex  items-center justify-between space-x-2">
            <div className="h-max overflow-hidden">
              <Image src={"/logo.svg"} width={30} height={30} alt="logo" />
            </div>
            <div className="  flex flex-col text-xs font-medium leading-tight">
              <span className="">Open for any</span>

              <span className="">collaborations and offers</span>
            </div>
          </div>
        </div>
        <div className="flex w-full justify-center">
          <h1 className="font-inter text-xl  font-bold">
            <Link className=" " href={"#"}>
              CODENN.
            </Link>
          </h1>
        </div>
        <div className="flex w-full justify-end">
          <div className="flex flex-col text-xs font-medium">
            <span>Portfolio</span>
            <span className="flex justify-end">
              Vol.1 <span>-</span>
            </span>
          </div>
        </div>
      </div>
    </>
  );
};

const Menu = () => {
  const [visible, setVisible] = useState(false);
  const [hoveredText, setHoveredText] = useState("Work");
  return (
    <>
      <div className="relative">
        <div className="relative z-50 flex items-center justify-between px-12 text-xs">
          <div
            className="cursor-pointer"
            onMouseEnter={() => {
              setVisible(true);
              setHoveredText("Work");
            }}
            onMouseLeave={() => setVisible(false)}
          >
            <p className=" font-medium text-[#878787]">01</p>
            <p
              className={clsx(
                "font-medium   mix-blend-difference  ",
                visible && " invert filter transition-colors duration-700"
              )}
            >
              Work
            </p>
          </div>
          <div
            className="cursor-pointer"
            onMouseEnter={() => {
              setVisible(true);
              setHoveredText("About");
            }}
            onMouseLeave={() => setVisible(false)}
          >
            <p className=" font-medium text-[#878787]">02</p>
            <p
              className={clsx(
                "font-medium   mix-blend-difference  ",
                visible && " invert filter transition-colors duration-700"
              )}
            >
              About
            </p>
          </div>
          <div
            className="cursor-pointer"
            onMouseEnter={() => {
              setVisible(true);
              setHoveredText("Playground");
            }}
            onMouseLeave={() => setVisible(false)}
          >
            <p className=" font-medium text-[#878787]">03</p>
            <p
              className={clsx(
                "font-medium   mix-blend-difference  ",
                visible && " invert filter transition-colors duration-700"
              )}
            >
              Playground
            </p>
          </div>
          <div
            className="cursor-pointer"
            onMouseEnter={() => {
              setVisible(true);
              setHoveredText("Contact");
            }}
            onMouseLeave={() => setVisible(false)}
          >
            <p className=" font-medium text-[#878787]">04</p>
            <p
              className={clsx(
                "font-medium   mix-blend-difference  ",
                visible && " invert filter transition-colors duration-700"
              )}
            >
              Contact
            </p>
          </div>
          <div
            className="cursor-pointer"
            onMouseEnter={() => {
              setVisible(true);
              setHoveredText("©2023");
            }}
            onMouseLeave={() => setVisible(false)}
          >
            <p
              className={clsx(
                "font-medium   mix-blend-difference  ",
                visible && " invert filter transition-colors duration-700"
              )}
            >
              ©2023
            </p>
          </div>
        </div>
        <AnimatePresence>
          {visible && (
            <motion.div
              className="absolute top-1/2  flex  w-full -translate-y-1/2 items-center justify-center overflow-hidden bg-black text-white  "
              initial={{ height: "0rem" }}
              animate={{ height: "9rem" }}
              exit={{ height: "0rem" }}
              transition={{ duration: 0.5 }}
            >
              <h1 className="text-center text-9xl ">{hoveredText}</h1>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </>
  );
};

export default Home;
