import { type NextPage } from "next";
import Head from "next/head";
import { Layout } from "../../components/layout/layout";

const Projects: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout page="design"></Layout>
    </>
  );
};

export default Projects;
